// saludo.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: mensaje.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaludoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaludoRequest) Reset() {
	*x = SaludoRequest{}
	mi := &file_mensaje_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaludoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaludoRequest) ProtoMessage() {}

func (x *SaludoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mensaje_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaludoRequest.ProtoReflect.Descriptor instead.
func (*SaludoRequest) Descriptor() ([]byte, []int) {
	return file_mensaje_proto_rawDescGZIP(), []int{0}
}

func (x *SaludoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type SaludoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaludoResponse) Reset() {
	*x = SaludoResponse{}
	mi := &file_mensaje_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaludoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaludoResponse) ProtoMessage() {}

func (x *SaludoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mensaje_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaludoResponse.ProtoReflect.Descriptor instead.
func (*SaludoResponse) Descriptor() ([]byte, []int) {
	return file_mensaje_proto_rawDescGZIP(), []int{1}
}

func (x *SaludoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_mensaje_proto protoreflect.FileDescriptor

const file_mensaje_proto_rawDesc = "" +
	"\n" +
	"\rmensaje.proto\x12\x06saludo\"'\n" +
	"\rSaludoRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\"*\n" +
	"\x0eSaludoResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje2I\n" +
	"\rSaludoService\x128\n" +
	"\aSaludar\x12\x15.saludo.SaludoRequest\x1a\x16.saludo.SaludoResponseB\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_mensaje_proto_rawDescOnce sync.Once
	file_mensaje_proto_rawDescData []byte
)

func file_mensaje_proto_rawDescGZIP() []byte {
	file_mensaje_proto_rawDescOnce.Do(func() {
		file_mensaje_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mensaje_proto_rawDesc), len(file_mensaje_proto_rawDesc)))
	})
	return file_mensaje_proto_rawDescData
}

var file_mensaje_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mensaje_proto_goTypes = []any{
	(*SaludoRequest)(nil),  // 0: saludo.SaludoRequest
	(*SaludoResponse)(nil), // 1: saludo.SaludoResponse
}
var file_mensaje_proto_depIdxs = []int32{
	0, // 0: saludo.SaludoService.Saludar:input_type -> saludo.SaludoRequest
	1, // 1: saludo.SaludoService.Saludar:output_type -> saludo.SaludoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mensaje_proto_init() }
func file_mensaje_proto_init() {
	if File_mensaje_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mensaje_proto_rawDesc), len(file_mensaje_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mensaje_proto_goTypes,
		DependencyIndexes: file_mensaje_proto_depIdxs,
		MessageInfos:      file_mensaje_proto_msgTypes,
	}.Build()
	File_mensaje_proto = out.File
	file_mensaje_proto_goTypes = nil
	file_mensaje_proto_depIdxs = nil
}
