// saludo.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: mensaje.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SaludoService_Saludar_FullMethodName = "/saludo.SaludoService/Saludar"
)

// SaludoServiceClient is the client API for SaludoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaludoServiceClient interface {
	Saludar(ctx context.Context, in *SaludoRequest, opts ...grpc.CallOption) (*SaludoResponse, error)
}

type saludoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaludoServiceClient(cc grpc.ClientConnInterface) SaludoServiceClient {
	return &saludoServiceClient{cc}
}

func (c *saludoServiceClient) Saludar(ctx context.Context, in *SaludoRequest, opts ...grpc.CallOption) (*SaludoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaludoResponse)
	err := c.cc.Invoke(ctx, SaludoService_Saludar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaludoServiceServer is the server API for SaludoService service.
// All implementations must embed UnimplementedSaludoServiceServer
// for forward compatibility.
type SaludoServiceServer interface {
	Saludar(context.Context, *SaludoRequest) (*SaludoResponse, error)
	mustEmbedUnimplementedSaludoServiceServer()
}

// UnimplementedSaludoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSaludoServiceServer struct{}

func (UnimplementedSaludoServiceServer) Saludar(context.Context, *SaludoRequest) (*SaludoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Saludar not implemented")
}
func (UnimplementedSaludoServiceServer) mustEmbedUnimplementedSaludoServiceServer() {}
func (UnimplementedSaludoServiceServer) testEmbeddedByValue()                       {}

// UnsafeSaludoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaludoServiceServer will
// result in compilation errors.
type UnsafeSaludoServiceServer interface {
	mustEmbedUnimplementedSaludoServiceServer()
}

func RegisterSaludoServiceServer(s grpc.ServiceRegistrar, srv SaludoServiceServer) {
	// If the following call pancis, it indicates UnimplementedSaludoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SaludoService_ServiceDesc, srv)
}

func _SaludoService_Saludar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaludoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaludoServiceServer).Saludar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaludoService_Saludar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaludoServiceServer).Saludar(ctx, req.(*SaludoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaludoService_ServiceDesc is the grpc.ServiceDesc for SaludoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaludoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saludo.SaludoService",
	HandlerType: (*SaludoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Saludar",
			Handler:    _SaludoService_Saludar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mensaje.proto",
}
